
version: "3.3"

services:

  web:
    build: .
    ports:
      - "5080:80"
    volumes:
      - ./html:/var/www/html
    networks:
      - n0

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=sample
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
    volumes:
      - ./sql/mysql_init_db.sql:/tmp/initdb.d/mysql_init_db.sql
      - ./sh/mysql_init_db.sh:/docker-entrypoint-initdb.d/mysql_init_db.sh
    networks:
      - n0

  pgsql:
    image: postgres:11
    environment:
      # User: postgres
      POSTGRES_PASSWORD: devpass
    volumes:
      - ./sql/pgsql_init_db.sql:/tmp/initdb.d/pgsql_init_db.sql
      - ./sh/pgsql_init_db.sh:/docker-entrypoint-initdb.d/pgsql_init_db.sh
    networks:
      - n0


networks:
  n0:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
